name: Prettier

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          prettier_options: --list-different --write app/assets/**/*.{js,css,scss}
          only_changed: true
          github_token: ${{ secrets.bundle_token }}
