name: Reviewdog

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  rubocop:
    name: Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
      - name: Rubocop
        uses: reviewdog/action-rubocop@v2
        with:
          rubocop_extensions: rubocop-rails rubocop-performance rubocop-thread_safety
          github_token: ${{ secrets.bundle_token }}
          reporter: github-pr-review

  brakeman:
    name: Brakeman
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Brakeman
        uses: reviewdog/action-brakeman@v1
        with:
          github_token: ${{ secrets.bundle_token }}
          reporter: github-pr-review
