name: StandardRB

on:
  workflow_call:
    secrets:
      bundle_token:
        required: true

jobs:
  standard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        env:
          BUNDLE_GITHUB__COM: x-access-token:${{ secrets.bundle_token }}
        with:
          bundler-cache: true
      - name: Run StandardRB
        uses: kirillplatonov/action-standardrb@v0.1.2
        with:
          github_token: ${{ secrets.bundle_token }}
          reporter: github-pr-review
          rubocop_flags: --format progress
          use_bundler: true
